apiVersion: v1
kind: Namespace
metadata:
  name: schoolspace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: schoolspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: appdb
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: apppass
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: schoolspace
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: schoolspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: schoolspace
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: schoolspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: schoolspace
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: schoolspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: appuser
            - name: RABBITMQ_DEFAULT_PASS
              value: apppass
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: schoolspace
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: schoolspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: school-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8040
          env:
            - name: DATABASE_URL
              value: mysql://root:root@mysql:3306/appdb
            - name: REDIS_URL
              value: redis:6379
            - name: MONGO_URL
              value: mongodb://mongo:27017/schoolapp
            - name: RABBITMQ_URL
              value: amqp://appuser:apppass@rabbitmq:5672
            - name: JWT_SECRET_KEY
              value: amazing_secret_key_yup_yes_abcdef123
            - name: JWT_SECRET_KEY_REFRESH
              value: amazing_secret_key_yup_yes_abcdef123
            - name: JWT_SECRET_KEY_VERIFY
              value: amazing_secret_key_yup_yes_abcdef123
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: schoolspace
spec:
  selector:
    app: backend
  ports:
    - port: 8040
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: schoolspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: school-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              value: mysql://root:root@mysql:3306/appdb
            - name: REDIS_URL
              value: redis:6379
            - name: RABBITMQ_URL
              value: amqp://appuser:apppass@rabbitmq:5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: schoolspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: school-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: schoolspace
spec:
  selector:
    app: frontend
  ports:
    - port: 3040
      targetPort: 80
  type: ClusterIP