FROM node:20-slim AS deps
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json ./

RUN npm install

COPY prisma ./prisma
RUN npx prisma generate

# ---------- Build ----------
FROM node:20-slim AS builder
WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

FROM node:20-slim AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN apt-get update -y && apt-get install -y openssl

COPY prisma ./prisma
COPY package*.json ./
COPY --from=builder /app/dist ./dist

RUN npm ci

EXPOSE 8040

CMD ["node", "dist/server.js"]
